### ISSUE TITLE
How to setup outdated

### ISSUE THREAD

**Issue by szimre** [A3Antistasi/A3-Antistasi#100]
There is no missionAltis.sqm file.

You probably have to use the files from the Templates directory.

**Comment by Barbolani77** [comment]
I dont know why GitHub is not adding it when I push. I Will need to ask the gith masters.

**Comment by zalexki** [comment]
the file in Templates/A3-AATemplate.Altis/mission.sqm is not ok ?

**Comment by Barbolani77** [comment]
it is, but there is no mission.sqm in the root folder, from any version

**Comment by zalexki** [comment]
hum ok so were just missing in the readme the part were you need to copy files in templates folder to the root folder ?
@szimre can you try that and if it works make a PR to update readme ? thank you.

**Comment by JamieKG** [comment]
you could do something like what Liberation do make its a lot more organised for multiple maps/mods I could even make some batch files to combine the framework with a said base mission.map

https://github.com/KillahPotatoes/KP-Liberation

**Comment by Barbolani77** [comment]
In some way that's how it's done, instead of root folders, it is under templates folder, so with just one download you have all the versions

**Comment by zalexki** [comment]
yes @JamieKG we have kind of the same system i just need someone to test and update readme if necessary or i'll do it but in a few weeks :/

**Comment by zalexki** [comment]
fixed
