### ISSUE TITLE
Untouched missions marked as completed, NATO agro growing

### ISSUE THREAD

**Issue by szimre** [A3Antistasi/A3-Antistasi#101]
*Version:* 1.1.3

*Mods:* none

*Environment*: MP dedi.

*.rpt attatched?* NO (no trace of issue)

*have you edited the missionfile?*: No 

***Issue:***

We keep getting notifications about unassigned, untouched missions getting completed, the faction receives the money and the agro grows. I'm not sure but it's probably every mission that times out comes up as completed.

**Comment by Barbolani77** [comment]
Thanks but lacks of lot of info.
