### ISSUE TITLE
MissionTanoa.tanoa missed

### ISSUE THREAD

**Issue by Raptorkoda** [A3Antistasi/A3-Antistasi#125]
*Version:* 1.0.4

*Mods:* RHS,FFAA,ACE NO Medical

*Environment*:MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***
la nueva version no tiene los archivos de tanoa ni de altis. la otra consulta es de los parametros a utilizar en un servidor dedicado en el server.cfg para definir los parametros del lobby (para que al reiniciar esten fijados y no que se deban fijar en el lobby con cada restart) / the new version does not have the tanoa or altis files. the other query is of the parameters to be used in a dedicated server in the server.cfg to define the parameters of the lobby (so that when restarting they are fixed and not that they should be fixed in the lobby with each restart) Google traductor

**Comment by Barbolani77** [comment]
los tienes dentro de templates, organizados por carpetas, copia - pega en el principal lo que haya ahí y ATPC :)
