### ISSUE TITLE
[issue] Dedicated Server Crash

### ISSUE THREAD

**Issue by vernaz92** [A3Antistasi/A3-Antistasi#129]
*Version:* 1.1.3

*Mods:* See RPT

*Environment*: MP dedi

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***

Dedicated server crashed twice in one day after different lengths of time. Server RPT shows error which might be related to ACE Frag module (File z\ace\addons\frag\functions\fnc_doSpall.sqf, line 49). Both crashes also happened when CSAT was attacking a NATO outpost (in a different location on the map), but that might just have been a coincidence. On restarting the mission, in both occasions, we were forced to restart from the beginning (maybe savegame was corrupted).

I attach:

- RPT of the server for the second crash (the first log file that was generated is over 6 GB large)
- RPT of my client for the second crash
[RPTServerClient.zip](https://github.com/A3Antistasi/A3-Antistasi/files/2173105/RPTServerClient.zip)
- Minidump generated for both crashes (https://drive.google.com/file/d/1rVNFx7KMKRF_jAQ6XPbWmDhRGWvmx9F8/view?usp=sharing and https://drive.google.com/file/d/1pYa1LjORcZY8tnzA3gYhNH2GEYmurj_R/view?usp=sharing)

---

**Comment by vernaz92** [comment]
By the way, our server has been used multiple times to host very large games (120+ players) with no issues

**Comment by Barbolani77** [comment]
Hi, this is an ACE error, not Antistasi. You should report there.

**Comment by neonoxd** [comment]
having the same issue now and we are not using ACE at all
