### ISSUE TITLE
Glitch del garage

### ISSUE THREAD

**Issue by Raptorkoda** [A3Antistasi/A3-Antistasi#130]
*Version:* 1.0.

*Mods:* CBA, TFAR, ACE(no-medical),RHS.FFAA

*Environment*:MP dedi.

*have you edited the missionfile?*: No

***Issue:***
Resulta que en mi servidor me he dado cuenta de un usuario el cual entra a su garage personal y al hacerlo aparece el vehiculo que quiere sacar, viene otro usuario y le da a garage vehicle cuantas veces quiera y sacara el mismo numero de vehiculos guardados. ejemplo: pone el m6a1 en la seleccion de garage y el compañero guarda 6 veces ese m6a1 y lo tendra 6 veces./ 

It turns out that on my server I have noticed a user who enters his personal garage and in doing so, he appears the vehicle he wants to take out, another user comes and gives the garage vehicle as many times as he wants, and he gets the same number of vehicles stored. example: put the m6a1 in the garage selection and the partner saves 6 times that m6a1 and will have it 6 times.

**Comment by zalexki** [comment]
if you are still in 1.0 i suggest you try the latest version (1.1.5)

**Comment by Barbolani77** [comment]
Solved
