### ISSUE TITLE
configurar server.cfg

### ISSUE THREAD

**Issue by Raptorkoda** [A3Antistasi/A3-Antistasi#131]
*Version:* 1.0.

*Mods:* CBA, TFAR, ACE(no-medical),RHS.FFAA

*Environment*:MP dedi.

*have you edited the missionfile?*: No

***Issue:***
tenia la duda respecto a la nueva version. en cuanto a los servidores dedicados. que lineas debo agregar a la configuracion para que los parametros esten fijados en cada restart?/I had the doubt about the new version. as for the dedicated servers. What lines should I add to the configuration so that the parameters are set in each restart?

**Comment by Barbolani77** [comment]
Ya tienes parámetros por defecto, sólo un admin los puede cambiar.

**Comment by Raptorkoda** [comment]
mi problema en general es: si yo como admin pongo en mi servidor que se requieran 50 armas para que se vuelva infinita. y se hace un restart programado y yo no estoy. vuelve a ser 25 ya que esta por defecto asi. la pregunta era si es que poniendo ciertos parametros en el server.cfg puedo fijar que sean 50 o que no esten seleccionables los NATO por ejemplo./my problem in general is: if I use admin I put on my server that 50 weapons are required so that it becomes infinite. and a scheduled restart is made and I am not. returns to be 25 since it is by default like this. the question was if it is that putting certain parameters in the server.cfg I can fix that they are 50 or that the NATO are not selectable for example.
Historial
Guardadas
Comunidad

**Comment by Barbolani77** [comment]
se puede, pero queda fuera del ámbito de Antistasi.

empieza aquí:

https://forums.bohemia.net/forums/topic/102554-howto-mapgame-parameters-in-servercfg/
