### ISSUE TITLE
Enhance membership management

### ISSUE THREAD

**Issue by zalexki** [A3Antistasi/A3-Antistasi#132]
Currently when you add a member in game if you win and start a fresh campaign it will get reset.
For now we have 2 solution for a persistent member list.

1. Add a simple condition to detect if filepatching is enable and in that case use an external file like community version was doing if i remember correctly. It will allow every dedicated servers to have a persistent member list and simple hosting ones will use current system (but will more probably be private ones so membership disabled)

2. Create a arma3 server side mod/addon to take care of it. (no idea what/how tho :/ )

**Comment by Sparker95** [comment]
I'll check out how to create a simple addon soon when I have some spare time. Doesn't seem to be hard to do.

**Comment by Sparker95** [comment]
Scratch my last comment. I've added a way to store data as a plain array as well as in a config-like form. So we can easily convert the 75 existing member entries into the new form.
https://github.com/Sparker95/AntistasiServerMembers/blob/master/AntistasiServerMembers/MemberList.hpp

**Comment by Barbolani77** [comment]
Yes. It is a Matter of converting to mod the mlist.sqf, adding just a control variable yo check in initserver.sqf. if the variable os not nil, then we are in an official server

**Comment by Xyaren** [comment]
Why not saving them in a variable on the servers profileNamespace? 
This is how ACE stores it's server settings for example.

Then you just need to modify the array when you add/ remove a member. 
The varaible would be cross mission+version persitent, and you don't need another mod.

**Comment by zalexki** [comment]
i think this is what is currently done and when we load fresh campain we loose members

**Comment by Xyaren** [comment]
It just has to be stored on a variable that is not wiped on a restart.

Alexis Haumaitre <notifications@github.com> schrieb am Di., 17. Juli 2018,
19:42:

**Comment by Sparker95** [comment]
I agree with you on profileNamespace but it's only good for once server.
But the problem is also to propagate new member UIDs to both of our servers. Currently we have two.

**Comment by Xyaren** [comment]
What a bout a TXT / CSV or anything else on the servers updated via FTP for example ( loaded with https://community.bistudio.com/wiki/loadFile )

( You would not need to restart the server after an update of the list ! )

**Comment by Sparker95** [comment]
We have considered this option as well. This command requires file patching to be enabled. You need to pass an option to the Arma server .exe file which is not allowed at all hosting services (like Nitrado).

**Comment by JamieKG** [comment]
how about using something like EXTDB3 and storing more in a mysql/maria database could you not also use this for other storage like anything currently saved in the profile I know its not a great idea due to users that play this in SP

**Comment by zalexki** [comment]
yep same problem this is not always available on basic hosting or SP like you said.

**Comment by zalexki** [comment]
thx @Sparker95 ! membership server mod is now available and already WIP for some improvements !
