### ISSUE TITLE
[Question] Why not using Functions Library

### ISSUE THREAD

**Issue by Xyaren** [A3Antistasi/A3-Antistasi#135]
I browsed the repository a bit and notec that this project is not using the [A3 Function Library](https://community.bistudio.com/wiki/Functions_Library_(Arma_3)) Feature.

They provide some benefits:

> 1. Automatic compilation upon mission start into a global variable - no need to remember direct paths to files.
> 2. Anti-hack protection using compileFinal (see Recompiling for more info)
> 3. Listing in the Functions Viewer
> 4. Advanced debugging options
> 5. Optional immediate execution upon mission start, without need for manual call
> 6. Potential performance improvements
From https://community.bistudio.com/wiki/Functions_Library_(Arma_3)#Adding_a_Function

Most importantly, I experienced a much cleaner code base and higher reusability after switching to functions.
If you are taking this in consideration, I would be happy to help transfering functionality to functions.
This can be a step by step process and would not affect active development.

**Comment by Barbolani77** [comment]
Yes, you are welcome to do so! I started this long time ago when the library was just born, and I just got used to the oldschool way.

**Comment by Sparker95** [comment]
Such an attempt has been already performed about two years ago. The people who were trying to do so gave up half way, I think.

**Comment by zalexki** [comment]
yes but as @Xyaren said it can be a step by step process and if he want to focus on that we well be happy to review and merge his progress with @Barbolani77 approbation :)
