### ISSUE TITLE
When barbolani learns how to make releases?

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#138]

**Comment by Barbolani77** [comment]
?????

**Comment by szimre** [comment]
He probably means that even though you create 'versions' with commits, you don't actually create releases, which usually mark stable points in the progress of the project, and the first place to look for downloads for those not into programming or GitHub (ex. https://github.com/KillahPotatoes/KP-Liberation/releases)

**Comment by zalexki** [comment]
@AlexTriada never :)
Barbolani does not take care of github, he only commit so community can help.

Due to beta stage and new version nearly every week i didnt want to start releases and last time i tried to automate a pbo creation with circleCI i failed.

If someone manage a free automatic way of creating pbos, i'll start creating proper release :)

**Comment by JamieKG** [comment]
if you were to take a look at how KP-Liberation does it im sure you can adapt to your needs im going to look myself out of interest I already spoke to the developer there about taking a look and adapting it and the reply was 

> Sure, it's all open source without any real conditions (just crediting the original author(s))

**Comment by zalexki** [comment]
@Sparker95 found something to use with addon builder and .bat file check https://github.com/A3Antistasi/A3-Antistasi-Membership.

He also found a gulp module : https://www.npmjs.com/package/gulp-armapbo which work when not using the compression. 

Waiting for bobchaos, but i'm confident that automated releases should come soon.

**Comment by anpage** [comment]
I know that this is closed now, but I went ahead and implemented some basic support for automatic release build and submitted a pull request: #150
