### ISSUE TITLE
Airstrikes not being saved

### ISSUE THREAD

**Issue by Nekuan91** [A3Antistasi/A3-Antistasi#140]
*Version:* 1.1.5

*Mods:* CBA, JSRS, Mag-Repack, Enhanced Movement

*Environment*:  MP dedi.

*.rpt attatched?* https://pastebin.com/aQnd0M5u

*have you edited the missionfile?*: No

Airstrike points not being saved. They can be used properly but will vanish upon server restart or when you return to lobby.

**Comment by Barbolani77** [comment]
thanks, solved in the next patch (already solved in github version)
