### ISSUE TITLE
Bleedout despite being fully healed and unconsciousness issues

### ISSUE THREAD

**Issue by clairmont32** [A3Antistasi/A3-Antistasi#141]
*Version:* 1.1.6

*Mods:* ACE, ACE Compat RHS (USAF, GREF, USAF), RHS USAF, GREF, USAF, ACE 2.12.2.33, CBA3, Advanced Rappelling, Advanced Urban Rappeling, EM, FFAA, Incon Effects Mod, Loot to Vehicle

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attached?*  Yep

*have you edited the missionfile?*: No

ACE Basic Medical issues seem to conflict with some Antistasi settings-

After coming back from being knocked unconscious (whether through medical healing or auto-recover, players cannot go into first-person mode or interact with items via scroll wheel. 

Additional issue is that players will continue to bleed out despite being fully healed (fully bandaged, more than 2 liters of blood, and morphine). We've looked at the mission through the editor and noticed a bleed out time that could not be disabled and its max value was 5 minutes. We did _**not**_ save the mission as I noticed your warnings in a SQF file that if we edit it, it's on us to fix (totally makes sense from a dev point btw). 

Please let me know if you need any further logs.
[arma3server_x64_2018-07-20_23-25-38.zip](https://github.com/A3Antistasi/A3-Antistasi/files/2215859/arma3server_x64_2018-07-20_23-25-38.zip)

**Comment by Barbolani77** [comment]
You are looking at the Antistasi revive Code which is disabled if you use Ace med, so there is no such interaction And none ACE med variable is touched.

If you experience issues with Ace, you should post there
