### ISSUE TITLE
Maybe you want to include some of this in your mission. 

### ISSUE THREAD

**Issue by jus61** [A3Antistasi/A3-Antistasi#142]
**Server Auto restart**
**kp_fuel_consumption.sqf**: This script handles the fuel consumption of vehicles, so that refueling will be necessary more often.
**tfar_channelcheck.sqf**

https://github.com/jus61/A3-Antistasi-KP/commit/b9daf363bf0509550b740feec13fc8e246b9da8c

**Comment by Sparker95** [comment]
Not sure about the mission itself, but as for our server, we are running a custom server-side TFAR enforcement script.
IMO it's better because at least you don't have the necessary TFAR settings hardcoded into the mission itself, but instead into a separate addon.

**Comment by jus61** [comment]
and auto restart?

**Comment by Sparker95** [comment]
Sorry, I can't say much about other features, it's rather a question to @Barbolani77 .
I just commented on this because we were implementing a similar TFAR script not long time ago.

**Comment by zalexki** [comment]
I like the idea of fuel and server auto restart too.

**Comment by Barbolani77** [comment]
Sorry, I never liked the fuel thing, as adds an additional logistic need which IMHO is not very fun (doesent require blow up things and kill soldiers)
