### ISSUE TITLE
Base Items Missing After Reload

### ISSUE THREAD

**Issue by firthy2151** [A3Antistasi/A3-Antistasi#143]
*Version:* (ALTIS) Current Steam Version (as of 22/07/18)

*Mods:* CBA, All RHS Mods

*Environment*: LAN

*.rpt attatched?* Yes (As ZIP file)

*have you edited the missionfile?*: No

***Issue:***

All base items (Arsenal, Rearm/Heal Crate, Flag, Map and Lamp) have disappeared upon server restart - only Petros has remained in his location from before the restart. 

As I don't have access to the flag in order to move the HQ normally, I have tried killing Petros (commander) or inciting a NATO attack to kill him for me to trigger the HQ replacement screen but this hasn't worked.

I did persistent save before exiting after my last session and all items were present when I did so, I also closed the server down properly.

Below is the RPT file:

[Arma3_x64_2018-07-22_18-30-35.zip](https://github.com/A3Antistasi/A3-Antistasi/files/2217262/Arma3_x64_2018-07-22_18-30-35.zip)

I'd appreciate your help in this issue, it has happened on earlier versions but my team and I weren't as far into our campaign and in the past decided to restart the mission completely.

Thank you
Firthy

EDIT: I forgot to mention, the items must be nearby our HQ complex and have not disappeared from the game entirely as this post may have initially portrayed as it is still possible to garage vehicles close to where the items were. I have searched in spectator mode around the complex and the surrounding area but haven't found anything.

**Comment by Barbolani77** [comment]
slved
