### ISSUE TITLE
[Bug] Garage key handling does not work

### ISSUE THREAD

**Issue by theZorro266** [A3Antistasi/A3-Antistasi#145]
*Version:* 1.1.5

*Mods:* None

*Environment*: MP dedi

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

When I enter my dedicated Linux server with a clean installation, Arma 3 1.80 (legacyport) and Antistasi from the workshop in version 1.1.5 I can play Antistasi, but I do have one issue. The (personal) garage does not react to any key inputs. Not for me or any of my friends. Two of us use Windows and one uses Linux with the same problem. The only way out is to press Escape and abort the mission. The console does not give me any error after entering the garage. It does however output some errors related to garage.sqf on the console on startup. I attached the full server console log.

If you need any other info, please tell me. I am a noob when it comes to Arma 3 mod/mission bug reporting :) Also I am sure I can compile the mod myself and maybe find the issue myself, if you point me into a direction.

Thanks a lot!

[ark-server.log](https://github.com/A3Antistasi/A3-Antistasi/files/2221448/ark-server.log)

**Comment by theZorro266** [comment]
I do get the feeling that this problem is about the `setPlateNumber` function which was added in 1.82 (https://community.bistudio.com/wiki/setPlateNumber). Is there any chance we could make the mission compatible with 1.80 but still use that function when using with Arma 3 1.82 ?

**Comment by Barbolani77** [comment]
Your mission is heavily bugged on init. Have you modified the scripts?

**Comment by theZorro266** [comment]
No, as stated. Have you read my second comment about functions added in 1.82? Do you know a way to use them, if they are available and fallback to other methods, if not? See https://community.bistudio.com/wiki/Category:Introduced_with_Arma_3_version_1.82 for all affected functions.

**Comment by Barbolani77** [comment]
I am far from my PC but I have seen your .rpt And bugs appear on init. This means its a mirarle you are even able to play. Will check It ASAP. The plate number is a minor issue compares with other bugs

**Comment by theZorro266** [comment]
@Barbolani77 the Arma 3 legacyports branch has received an update to 1.82 just 30 minutes ago. I will retest ASAP and keep you up to date on this issue.

**Comment by theZorro266** [comment]
Okay, I can confirm that it indeed was a problem with version 1.80. 1.82 works fine. I will have to keep a look on the legacyports versions then :) Thanks a lot for your fast responses and the urge to find the issue @Barbolani77
