### ISSUE TITLE
[bug] no resource give back for dismissed units when undercover

### ISSUE THREAD

**Issue by ROMB** [A3Antistasi/A3-Antistasi#148]
*Version:* 1.2.2

*Mods:* CBA, RHS-AFRF, RHS-USAF, RHS-GREF + ACE compatibility modules for them, ACE(no-medical)

*Environment*: MP lan host.

*.rpt attatched?* [Arma3_x64_2018-07-29_11-05-44.zip](https://github.com/A3Antistasi/A3-Antistasi/files/2238521/Arma3_x64_2018-07-29_11-05-44.zip)

*have you edited the missionfile?*: No

***Issue:***

Dismissing units in undercover mode does not give resources back.
Easily reproducible: start Antistasi, hire unit, go undercover, dismiss unit.
Expected result: resources for the unit given back.
Actual result: no resources given back (permanent loss of HR and money).

**Comment by Barbolani77** [comment]
solved in the next patch, thanks!
