### ISSUE TITLE
Personal and Faction Garage vehicle selection causing issues

### ISSUE THREAD

**Issue by Metseven3** [A3Antistasi/A3-Antistasi#153]
*Version:* 1.0.

*Mods:* the issue doesn't involve mods

*Environment*: MP dedi.

*.rpt attatched?* NO

*have you edited the missionfile?*: No

***Issue:***

---
Hello, My friends and I have been playing this mod for a while now but one issue we've noticed is when you move your HQ to certain locations and try to take a vehicle out of the personal or faction garage, we sometimes get killed by the vehicle if it hits the flagpole, or as we select which one we want, it will bounce off the scenery around it (Try selecting a truck, truck is placed near tree and glitches and flies away, etc.). I was just wondering if it would be possible to implement a system where the vehicles don't move around so much when you select them, so you can know where exactly a vehicle will be spawned so as to limit the amount of accidents that can happen

On another note, the civilians appear to not see (or care) about our vehicles when we're on the road. I was out next to my truck sorting my gear and a civilian boxtruck crashed right into me, blowing himself and my truck up. I don't know what exactly might be causing such issues of suicidal civilians but I thought it was an issue enough to make a mention of it,

**Comment by zalexki** [comment]
The author is not that much available right now tho we will see when he come back.

In the meantime moove the flagpole away from the HQ on flat ground :)

**Comment by Metseven3** [comment]
Yeah we already did that after the second vehicular manslaughter haha but I was more so just suggesting maybe an option to have a set static placement of vehicle spawn

**Comment by Barbolani77** [comment]
This is solved and heavily improved
