### ISSUE TITLE
[bug] [question] AFRF Punishement triggered at 7 AGGRO 

### ISSUE THREAD

**Issue by Neeqza** [A3Antistasi/A3-Antistasi#154]
*Version:* 1.0.

*Mods:* CBA, RHS, bunch of weapons mods

*Environment*: SP

*.rpt attatched?* NO

*have you edited the missionfile?*: No

***Issue:***
Hello, I don't really know if this is a bug or a new feature but in my SP campaign, which is rather new (still in the beginning, no outpost, around 30 ChKzD aggro and 7 AFRF aggro), a "AFRF Punishement" mission poped up. The town attacked is Molos, the closet town to the default AFRF airbase and my HQ is around the default location, making it impossible to defend. I thought punishement were triggered at high aggro levels, so is this new or is it just a bug ?

Thank you
---

**Comment by Barbolani77** [comment]
Aggro os not related to punishments
