### ISSUE TITLE
[Bug] ACE medical does not work

### ISSUE THREAD

**Issue by llwolf** [A3Antistasi/A3-Antistasi#155]
*Version:* Most recent version on Steam Workshop as of Aug 9th

*Mods:* CBA, ACE

*Environment*: SP, MP LAN

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
ACE gets detected on startup, however after reviving an AI with ace, they become unresponsive, with an option to revive them using the scroll wheel, altough you are unable to do it, because it requires a first aid kit. There is no option in the parameters to disable normal medical as an alternate way to prevent this issue from happening.
![20180809133333_1](https://user-images.githubusercontent.com/37505300/43896786-4c97b4ac-9bda-11e8-97aa-95534b72af45.jpg)
![20180809133452_1](https://user-images.githubusercontent.com/37505300/43896788-4cba0200-9bda-11e8-994b-e4a8cef2bd44.jpg)
![basicallyvanilla](https://user-images.githubusercontent.com/37505300/43896800-578faf0e-9bda-11e8-8660-798e97b8fcdf.PNG)
![lobby](https://user-images.githubusercontent.com/37505300/43896801-57f76004-9bda-11e8-8ed6-9bdc7691ea8c.PNG)
![parameters](https://user-images.githubusercontent.com/37505300/43896803-58b1c76e-9bda-11e8-8168-cc4abc9e65ea.PNG)

**Comment by zalexki** [comment]
ace medical never worked and was never supported, read description.

**Comment by llwolf** [comment]
Hey, the description on steam does not mention medical, and bamboolani claims ace medical works, also it says when detecting ace that ace medical replaces medical system.

**Comment by zalexki** [comment]
hum i thought that ace medical should disable the revive system (you shouldnt have the scroll menu), tho for sure it will make the AI to not be able to revive you.

Any way consider ACE medical to fuck up Antistasi revive system, on official servers we play with ace no medical, check the readme on github.

**Comment by Barbolani77** [comment]
What Antistasi does when detects Ace med is just to disable Antistasi feature. I may check but prolly is more an ACE fail
