### ISSUE TITLE
RHS Vehicles are free?

### ISSUE THREAD

**Issue by Jlalond** [A3Antistasi/A3-Antistasi#157]
*Version:* 1.2.5.

*Mods:* CBA, TFAR, USAF, AFRF, GREF, no ace

*Environment*: MP dedi

*have you edited the missionfile?*: No

***Issue:***

---

It seems we can spawn vehicles for free? Seems weird. Not sure if bug or intentional but is such a strange shift from previous antistasi that suddenly helicopters are free.

**Comment by Barbolani77** [comment]
¿?¿? of course if those are free it is a bug!!! But with this info I can do very little, I need you to post exactly what's the issue, how you reproduce it etc.

**Comment by Jlalond** [comment]
@Barbolani77 It was due to CBA being outdated it seemed, updated it and it solved all my problems. Weird. TY for your continued work
