### ISSUE TITLE
[bug?] Riflemen manning static weapons disappear between saves

### ISSUE THREAD

**Issue by Puciek** [A3Antistasi/A3-Antistasi#162]
*Version:* 1.3.3

*Mods:* CBA, TFAR

*Environment*: SP

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
I was wondering why my count in garrisons keeps going down between reloads of the game, and yet they were not attacked. I finally managed to narrow it down to the fact that I have static weapons deployed (the AT and AA cannons you can purchase from flag) and the rifleman that man them after reload, disappear on next reload - with no cash refund. I understand that crews in vehicles do not save through persistent save option (it's in the warning) but as those are garrison forces I cannot tell them to man/unman weapons, so it's kinda annoying and a bit expensive to replace those riflemen every reload.

Is there some workaround for it? Or maybe a way to fix it? A command for garrisons to mount/dismount weapons would do it, could do that before a save and then order a mount up afterwards.

**Comment by Barbolani77** [comment]
Uhm, annoying. That message is not meant for garrison units but for your squadmates. The garrisons are saved in a separate script, and the garrison content is in a variable which only changes when you kill the unit or lose / modify the garrison. I have to check this.

**Comment by Puciek** [comment]
Thanks, @Barbolani77 I can reproduce this every single time so I imagine the same will apply to any game. But if not, let me know and I will upload the rpt.

**Comment by Barbolani77** [comment]
got it, solved in the next patch!

**Comment by Puciek** [comment]
@Barbolani77 Perfect, thank you! Any chance to get a sneak preview of just that one fix? ;)

**Comment by Barbolani77** [comment]
Yes, prolly tonight I will upload a pre public release on github

**Comment by Barbolani77** [comment]
Updated!

**Comment by Puciek** [comment]
Great stuff mate, appreciated! Any idea where it will make to workshop? Either way will check it out tomorrow :).
