### ISSUE TITLE
Suggestion: Backup loading system for vehicle cargo

### ISSUE THREAD

**Issue by Takahashi-Yuuki** [A3Antistasi/A3-Antistasi#165]
Hello. I have been for the past few weeks working on porting Antistasi to Takistan using the CUP mods. However, I seem to have run into a problem with the distribute supplies mission. The crate will not fit in any CUP vehicle. They do not seem to be configured in a way that the current cargo system can make use of. This unfortunate fact threatens my whole endeavor.

Thus, a backup system of sorts to accommodate mods that do not work with the primary system would be appreciated and a great boon to future mission porters.

**Comment by Barbolani77** [comment]
I had the same problem when building AK. The main thing is Jeroen for some reason didnt implemented an "automated way to find free space" if that's even possible in Arma.

Definetly far of my skills ATM
