### ISSUE TITLE
Mortars won't be manned - incorrect variable name

### ISSUE THREAD

**Issue by wriley** [A3Antistasi/A3-Antistasi#166]
Thanks for an awesome mission!

*Version:* 1.3.x

*Mods:* CUP Terrains, CBA, IFA3

*Environment*: SP

*.rpt attatched?* NO

*have you edited the missionfile?*: No

***Issue:***

M2 mortars weren't being manned by garrisoned troops on Armia Krajowa. Found error in RPT and simple fix.

in CREATE\createSDKgarrisons.sqf around line 84 use _x loop variable instead of _estatica

if (typeOf _x == SDKMortar) then
	{
	_unit = _grupoMort createUnit [(_garrison select _index), _posicion, [], 0, "NONE"];
	_unit moveInGunner **_x**;
	_nul=[**_x**] execVM "scripts\UPSMON\MON_artillery_add.sqf";

**Comment by Barbolani77** [comment]
Thanks a lot! Will be corrected in the next patch
