### ISSUE TITLE
1.3.5 - Outposts AK owns and garrison show as Wehrmacht on map

### ISSUE THREAD

**Issue by wriley** [A3Antistasi/A3-Antistasi#168]
*Version:* 1.3.5 (WW2 version)

*Mods:* CBA_A3, CUP Terrains - Core, CUP Terrains - Maps, IFA3_AIO_LITE, JSRS SOUNDMOD, Enhanced Movement

*Environment*: SP

*.rpt attatched?* YES
[Arma3_x64_2018-10-16_11-25-22.txt](https://github.com/A3Antistasi/A3-Antistasi/files/2484117/Arma3_x64_2018-10-16_11-25-22.txt)

*have you edited the missionfile?*: No

***Issue:***

Loading up a save from 1.3.3 - outposts I (AK) own show on the map as German (blue, Wehrmacht). If I go to the outpost (fast travel works) I see my own men (AK) garrisoned there. Same for factories and resources that I have conquered, they all show as blue instead of green. Towns appear to be correct.

attaching vars file 
[Kerbo.vars.Arma3Profile.zip](https://github.com/A3Antistasi/A3-Antistasi/files/2484140/Kerbo.vars.Arma3Profile.zip)

If this is too early to report issues for 1.3.5 then I apologize. I was testing 1.3.5 hoping for better performance. I can't really play 1.3.4 (or 1.3.5) because fps goes to less than 10. 1.3.3 works fine.

**Comment by Barbolani77** [comment]
Yep. Has been reported un other section. Is a load problem solved in the next patch! Thanks And do not apologise for a nice bug report!

**Comment by wriley** [comment]
Great, thank you
