### ISSUE TITLE
error after respawn

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#170]
No entry ‘bin\config.bin/CfgWeapons.DefaultManGuerillaLinkedItems’.

**Comment by Barbolani77** [comment]
??? Is there anything in Gameplay related yo that line in the .rpt? Because thats the usual spam that BIS does on .rpt not related to the mission maker scripts

**Comment by AlexTriada** [comment]
it is in gameplay, not in rpt

**Comment by Barbolani77** [comment]
oh! Also, anyway, BIS spam, mod related, google it and you will see
