### ISSUE TITLE
Blinking enemy vehicles

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#171]
Version: <=1.3.5.2
Mods: CBA, TFAR, all RHS
Environment: MP dedi.
.rpt attatched? No
have you edited the missionfile?: No

Issue:

After a grenade hits an enemy vehicle, it does not explode and begins to twitch and blink, about once a second, and it becomes more difficult to hit, because the amount of damage caused to it as if reduced. Honestly, why would you want to hang a script on damage to equipment, appliances and all so right in the original Arma.

**Comment by AlexTriada** [comment]
please remove all scripts from damage to vehicles and bots, or at least make it a disable option

**Comment by Barbolani77** [comment]
Antistasi has nothing on damage process on vehicles from fire of any weapon. Even less to make grenades dont explode. Why you say so? And again, without any support to check the issue I can do nothing.

**Comment by AlexTriada** [comment]
Antistasi has nothing on damage process on vehicles from fire of any weapon. Even less to make grenades dont explode. Why you say so? And again, without any support to check the issue I can do nothing. -
OK
but your mission errors or wrong sqript do so, pls fix this bug
