### ISSUE TITLE
Code error in onPlayerDisconnect.sqf after headless client disconnects.

### ISSUE THREAD

**Issue by enxyo** [A3Antistasi/A3-Antistasi#174]
onPlayerDisconnect.sqf - line 70

`if ((owner _unit) in hcArray) then`

if statement is not true in case of a headless client disconnecting.

As far as I can tell `owner _unit`, in this case, is the server and there therefore not in `hcArray`.
My understanding is you can not get the playerID of a client after he disconnected. `hcArray` holds the playerID of all headless clients.

I made a fix by myself but I'm not familiar with SQF and there is probably a better way. Trying to avoid breaking something else, I introduced a `hc2Array` and used that instead of the `hcArray`.

Code can be found here:

https://github.com/A3Antistasi/A3-Antistasi/compare/master...enxyo:enxyo-patch-1

**Comment by Barbolani77** [comment]
To be honest, totally untested but AFAIK the EH which executes the script fires before doing anything else from the server side, so it should work. Have you tested? I cannot do it on my PC because I still dont know how to make the server not kicking my HC (BattleEye thing)

If not, there is a cheapest way, as the EH provides the owner in _this select 4. See here: https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#PlayerDisconnected

**Comment by AlexTriada** [comment]
> To be honest, totally untested but AFAIK the EH which executes the script fires before doing anything else from the server side, so it should work. Have you tested? I cannot do it on my PC because I still dont know how to make the server not kicking my HC (BattleEye thing)

-write a line how you starting HC, and are steam is starting or not?

**Comment by Barbolani77** [comment]
I do it in the most simple way: from steam launcher I launch my client, a dedi and a headless. Dedi works ok, but the HC gets kicked.

**Comment by AlexTriada** [comment]
problem is in steam account - the dedi start with same steam acc as the HC
you dont need start steam at all when you starting dedi and HC

**Comment by AlexTriada** [comment]
start dedi and HC wuthout steam- and after you may start steam and start client

**Comment by AlexTriada** [comment]
try copy this in the bat file and put bat in arma 3 folder then start
start /min arma3server_x64.exe -client -connect=127.0.0.1 -port=2502 -nosound -profiles="C:\A3DS3\profiles\HC1" -hugepages -maxMem=12288 -enableHT -mod=""
arma3server_x64.exe -port=2502 -nosound -profiles="C:\A3DS3\profiles" -name=Server -config=Antistasi.cfg -hugepages -maxMem=12288 -mod=""

**Comment by AlexTriada** [comment]
paths "C:\A3DS3\profiles\HC1" and "C:\A3DS3\profiles" - you select youself

**Comment by Barbolani77** [comment]
thanks!

**Comment by AlexTriada** [comment]
or find and set this in dedi config
kickDuplicate        = 0;

**Comment by Barbolani77** [comment]
solved with _owner = _this select 4. Thanks anyway!
