### ISSUE TITLE
Blinking enemy vehicles

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#175]
Version: <=1.3.5.2
Mods: CBA, TFAR, all RHS
Environment: MP dedi.
.rpt attatched? No
have you edited the missionfile?: No

Issue:

After a grenade hits an enemy vehicle, it does not explode and begins to twitch and blink, about once in a two second, and it becomes more difficult to explode, pls fix this BUG.

**Comment by enxyo** [comment]
Sounds very much like a non antistasi issue, do you have any video/image?

**Comment by Barbolani77** [comment]
It is definetly not Antistasi

**Comment by AlexTriada** [comment]
Dude, you are terribly wrong, can certainly these glitches you have not, but that does not mean that it is not related to Antistasi, my server settings are different from yours, I have the membership disabled, etc

**Comment by Barbolani77** [comment]
You doubled post this and it is not an Antistasi bug. Closing.

**Comment by AlexTriada** [comment]
> You doubled post this and it is not an Antistasi bug. Closing.

yes, because this is a Antistasi bug - you wrong

**Comment by AlexTriada** [comment]
it feels like you don't want us (or me) to write you about bugs in the mission

**Comment by Barbolani77** [comment]
Alex it feels like you don't trust the guy that has been working on this and tells you this is not an Antistasi bug. Keep calm and think if I tell you this is totally unrelated, the most probably thing is that...it's unrelated.

Of course you are more than welcome to report bugs, but you are not welcome to troll the site and spam me with "no you are wrong". If you still think I am wrong, first of all you should post the report properly, which you are not doing by far, and from there, we will see.

And please save your personnal opinions for yourself, this is not the place.

**Comment by AlexTriada** [comment]
Ok, i understand you, i want to help) Not spam and troll)
