### ISSUE TITLE
Lost 0 (I could be wrong)

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#178]
https://github.com/A3Antistasi/A3-Antistasi/blob/f58f7e40e1fc860bef0f1c177d639219737e3158/A3-Antistasi/defines.hpp#L107

must be:
colorText[] = {1,1,1,0.5};

**Comment by Barbolani77** [comment]
Same as the other: no, as long as you may see the statistics bar.

**Comment by AlexTriada** [comment]
why don't you fix it? or don't you want to make it nice?
