### ISSUE TITLE
Are class names start with number is not error?

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#179]
i dont know error this or not, but syntax check in sqflinter for vs code is mark this as error
https://github.com/A3Antistasi/A3-Antistasi/blob/f58f7e40e1fc860bef0f1c177d639219737e3158/A3-Antistasi/dialogs.hpp#L1554

- and many more syntax like this in this file

**Comment by Barbolani77** [comment]
Nope, as long as the script works, and it does (it's the statistics bar you see top of the screen)
