### ISSUE TITLE
[bug] can't revive "it's beeing carried"

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#18]
*Version:* 0.11.1.C

*Mods:* CBA, TFAR ACE no medical

*Environment*: MP dedi

*.rpt attatched?* Nothing on it

*have you edited the missionfile?*: Yes

***Issue:***
We took mortar fire, one player in my group went unconscious, my AI tried rescue and died after carry begin. 
We couldn't get him up because he was "beeing carried" nor the AI, once revived, managed to get him back up.

**Comment by Barbolani77** [comment]
broke my head but I cannot find any reason to this bug,

**Comment by StefArma** [comment]
Well is there a way to reset the thing manually? Maybe a Y menu button that reset the carry status so.. just in case, we've the antidote.. (i'll think about the button no worries)

**Comment by Barbolani77** [comment]
found a possible reason and we will see in the next patch

**Comment by Barbolani77** [comment]
solved
