### ISSUE TITLE
[bug] Disconnect issue

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [A3Antistasi/A3-Antistasi#197]
*Version:* 1.4.0.1

*Mods:* CBA, TFAR

*Environment*: MP dedicated

*.rpt attatched?* No

*have you edited the missionfile?*: Yes (add TFAR system component)

***Issue:***

---

```
 1:50:01 Player Jonathan disconnected.
 1:50:01 BattlEye Server: Player #0 Jonathan disconnected
 1:50:01 Client: Remote object 3:0 not found
 1:50:01 "antistasi-altis/BIS_fnc_log: HandleDisconnect : R Alpha 1-6:1"
 1:50:01 Error in expression <er _x} count (units _x) == 0) and (side group _x == buenos)) then
{
_uds = units>
 1:50:01   Error position: <group _x == buenos)) then
{
_uds = units>
 1:50:01   Error group: Type Group, expected Object
 1:50:01 File onPlayerDisconnect.sqf [A3A_fnc_onPlayerDisconnect], line 14
 1:50:01 Error in expression <er _x} count (units _x) == 0) and (side group _x == buenos)) then
{
_uds = units>
 1:50:01   Error position: <group _x == buenos)) then
{
_uds = units>
 1:50:01   Error Generic error in expression
 1:50:01 File onPlayerDisconnect.sqf [A3A_fnc_onPlayerDisconnect], line 14
```

**Comment by wriley** [comment]
Changing this on line 14 fixes this error.

side group _x == buenos   ---->  change to ----> side _x == buenos

This also made personal stats save work again when using ACE on a dedi server. With this error present it seems to corrupt the personal stats save, at least for loadout and personal garage when using ACE mod. Fixing this error made it work again for me.

**Comment by Mocksybren** [comment]
are you using full ace or the Antistasi ACE?

**Comment by Barbolani77** [comment]
???? That line is supposed to be fixed in the current latest update

**Comment by wriley** [comment]
> ???? That line is supposed to be fixed in the current latest update

https://github.com/A3Antistasi/A3-Antistasi/blob/master/A3-Antistasi/onPlayerDisconnect.sqf#L14

It's still there on master on github for me. Maybe a fix that didn't get pushed?

**Comment by Jonathan-Rosewood** [comment]
onPlayerDisconnect.sqf (in 14 line)
```diff
	if (!(_x getVariable ["esNATO",false])) then
		{
+		if ((leader _x getVariable ["spawner",false]) and ({isPlayer _x} count (units _x) == 0) and (side _x == buenos)) then
-		if ((leader _x getVariable ["spawner",false]) and ({isPlayer _x} count (units _x) == 0) and (side group _x == buenos)) then
			{
			_uds = units _x;
```

**Comment by Barbolani77** [comment]
Yes, it seems I messed up with something while pushing, on the next one!

**Comment by Barbolani77** [comment]
Solved!
