### ISSUE TITLE
[proposal] Localization

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [A3Antistasi/A3-Antistasi#201]
https://community.bistudio.com/wiki/Stringtable.xml

It would be nice if this mechanism was implemented in a mission.
I am personally ready to help with the Russian translation.

**Comment by Jonathan-Rosewood** [comment]
So, i starts making localization support and oh god...who write this shit?!
Some vague comments that mean nothing or are simply outdated, inconsistency of variable names (complete absence of semantics).
I apologize, of course, but there is no desire to continue digging through this shit. If the developer supporting this project so disregarding applies to those who want to make any changes. Such shame should be hidden in private repositories and not put on display (IMHO).
http://prntscr.com/lieno5

**Comment by Barbolani77** [comment]
???? To be honest, I don't understand what is the problem if by copypasting code structures I don't change subclasses, which is totally irrelevant and creates zero bugs, it affects on anything the ingame texts which are related to the topic.

This would be a GREAT addition, yes.

**Comment by Jonathan-Rosewood** [comment]
This affects the readability of the code and its perception.
