### ISSUE TITLE
[bug] Freshly pulled vehicles do not retract into the garage.

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [A3Antistasi/A3-Antistasi#203]
*Version:* 1.4.0.2

*Mods:* CBA, TFAR

*Environment*: MP dedicated

*.rpt attatched?* Partialy on video

*have you edited the missionfile?*: Yes (add TFAR systems only)

***Issue:***

---
https://youtu.be/POVBM-GOfcc

**Comment by Barbolani77** [comment]
It is an Arma engine thing. The command that checks the object you are looking needs some time to detect freshly spawned vehicles.

**Comment by jahangir13** [comment]
Zooming in with the right mouse button to the object/vehicle helps. Not sure if this is only my personal feeling, hm.
What could work is the reveal command (https://community.bistudio.com/wiki/reveal    ,see comment from Doolittle), but I was unsuccessful trying it. Maybe I found the wrong place of the create vehicle command.
But however, who needs to un-garage a vehicle and directly garage it in again ;)
