### ISSUE TITLE
[bug] City Supplies mission

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [A3Antistasi/A3-Antistasi#207]
*Version:* 1.4.0.2

*Mods:* CBA, TFAR, ACE (no-medical)

*Environment*: MP dedi.

*.rpt attatched?* Partially

*have you edited the missionfile?*: Yes (TFAR system)

***Issue:***

---

1. Complete 'City Supplies' mission.
2. Dead then respawn.
3. Try to take mission again - nothing happens.

```
21:05:11 "antistasi-altis/log: ERROR: [BIS_fnc_taskType] Task 'LOG' does not exists."
```

**Comment by Barbolani77** [comment]
Sidemissions have a cooldown, after some time you should be able to ask again. Petros should tell it.
