### ISSUE TITLE
[bug] Vehicle shop

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [A3Antistasi/A3-Antistasi#208]
*Version:* 1.4.0.2

*Server Mods:* CBA, TFAR, ACE (no-medical)
*Client Mods:* CBA, TFAR, ACE (no-medical), RHS bundle (AFRF, USAF, GREF)

*Environment*: MP dedicated

*.rpt attatched?* No

*have you edited the missionfile?*: Yes (TFAR system)

***Issue:***

---

Since the list of vehicles for purchase is generated on the client, this causes errors in pricing.
Screenshots: https://imgur.com/a/I7Wn9i8

**Comment by Barbolani77** [comment]
uhmuhm, the prices are saved in a global variable which is used by the client. When you buy it, what is the money reduced with the right price?

**Comment by Jonathan-Rosewood** [comment]
Yeah, got it, thanks. But it would be nice to fix the visual part and, in general, the possibility of acquiring equipment from non-activated mods on the server.

**Comment by Barbolani77** [comment]
Sorry, I don't get what you mean.

**Comment by Jonathan-Rosewood** [comment]
When the RHS is not used on the server, players can still buy vehicles from this modification.

**Comment by Barbolani77** [comment]
oh! But thats totally on the server admin side!!!
