### ISSUE TITLE
[AI suggestion] AI shouldn't dismount an AA/AT truck after losing a few tires

### ISSUE THREAD

**Issue by iskela45** [A3Antistasi/A3-Antistasi#209]
*Mods:* CBA, TFAR, ACE, RHS AFRF, USAF and GREF

*Environment*: MP dedi

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

---

Change the AI so it doesn't dismount the ZU-23-2 and other unarmored military vehicles/technicals.

Not sure how hard this would be to implement but playing as GREF commander often boils down to remote controlling dismounted ZU-23-2 truck crews to shoot down incoming helicopters. The vehicle and crew survive most of the time but as soon as a helicopter door gunner shoots them or HE ammo lands anywhere near the truck most of the wheels break and the AI dismounts even if they could defend themselves by manning the AA gun. 3 man squad can do a lot more with an immobile ZU-23-2 than they can with their assault rifles. In most cases the mobile AA is already in a position where the commander wants it.

This also applies to the self propelled SPG-9.

**Comment by Mocksybren** [comment]
AI dismounts when they are immobile, that is base arma code. it is possible to code them so they won't dismount after being immobelized but that gives the issue that you barely can take an tank or an IFV.
