### ISSUE TITLE
Antistasi medical not turning off

### ISSUE THREAD

**Issue by iskela45** [A3Antistasi/A3-Antistasi#210]
*Version:* 1.4.0.2

*Mods:* CBA, TFAR, ACE, RHS, RHS ACE compat

*Environment*: MP dedi.

*have you edited the missionfile?*: No

***Issue:***

---

Is there a way to manually disable the antistasi medical system as it isn't automatically turning off when it detects ace medical and sometimes leaves enemies in this confusing limbo where they're in the antistasi downed state instead of the ace medical downed state. They cannot be killed unless you throw grenades at them or use ace medical to give them an epipen to maybe wake them up so you can kill them again. The surrendering and other parts of the AI work as intended.

**Comment by Mocksybren** [comment]
Turn off AI unc it causes issue's with the Antistasi medical, i know it sucks but then you can lower the agression you guys produce with Friendly AI medics and the Enemy AI Drags wounded guys etc.
