### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by teemo0803** [A3Antistasi/A3-Antistasi#224]
Dear Author，
         Im an Antistasi player from China,there are plenty of people fond in this perfect missions.I wonder if  you can add `stringtable.xml` to the missions file so that i can translate it to Chinese.
                                                                                                                                   sincerely,
                                                                                                                                   Teemo

**Comment by barman75** [comment]
I am working on adding stringtable.xml now. But progress is slow due the lack of time.

**Comment by teemo0803** [comment]
> I am working on adding stringtable.xml now. But progress is slow due the lack of time.

Thanks a lot
Teemo
