### ISSUE TITLE
[minor error] JNA additem 

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#42]
*Version:* 0.12.0A

*Mods:* CBA, TFAR, ACE no medical

*Environment*: SP & MP dedi.

*.rpt attatched?* YES highlight below

*have you edited the missionfile?*: Yes

***Issue:***

    19:03:32 Error in expression <"_index","_item",["_amount",1]]; _array set [_index,[[_item,_amount]]]; }else{ _>
    19:03:32   Error position: <set [_index,[[_item,_amount]]]; }else{ _>
    19:03:32   Error Zero divisor
    19:03:32 File JeroenArsenal\JNA\fn_arsenal_addItem.sqf [JN_fnc_arsenal_addItem], line 1262

might be caused by ACE no medical

also i notice that Cable Tie get "unlocked" every game tick.
Very low priority on this, just noticing

**Comment by StefArma** [comment]
another error related to jna

    18:37:46 Error in expression <me = getText(configfile >> "CfgWeapons" >> _item >> "tf_parent"); if!(_radioName>
    18:37:46   Error position: <>> _item >> "tf_parent"); if!(_radioName>
    18:37:46   Error >>: Type Array, expected String
    18:37:46 File JeroenArsenal\JNA\fn_arsenal_addItem.sqf [JN_fnc_arsenal_addItem], line 1279

**Comment by Barbolani77** [comment]
This happens when for example you add an RHS classname without the mod installed. Anyway I bulletproofed a bit more that function just to avoid error report.
