### ISSUE TITLE
[Refactoring] All source code should be refactored in a object-oriented programming

### ISSUE THREAD

**Issue by zalexki** [A3Antistasi/A3-Antistasi#44]
For a better readability and maintainability of the project, the source code should implement various software design patterns and loose the procedural programming for an oriented-object one.

Example [here](https://github.com/zalexki/Antistasi-WotP/pull/1/files) (probably not functionnal as i started SQF yesterday)

Also as the code base is already pretty huge and refactoring all code at once is a no go, i suggest implementing object-oriented programming step by step.

**Comment by Sparker95** [comment]
As I know SQF doesn't support classes (don't confuse with classes in .cfg files) or object-oriented things without extentions. Do you use some extention to get class support?

**Comment by zalexki** [comment]
Hum i see, so https://community.bistudio.com/wiki/Class_Inheritance is only for config files ? i cry :(
But i think we still can have a more object-oriented code (or at least DRY), simply on mission files i can see that [all this dificil condition](https://github.com/A3Antistasi/Antistasi-WotP/blob/master/WotP.Tanoa/Missions/AS_Oficial.sqf#L11-L92) is repeated, this should be refactored in a function (or at least mooved into a isDificil.sqf file and then included) and also get a linter on it.
 
We call also look at some plugins to do that like this [one](https://github.com/code34/oop.h/wiki).

**Comment by StefArma** [comment]
i think that _difficil is the same only because it was an initial copypaste... however each mission might be improved and with different conditions after the mission core is done (this is still alpha).

So, making a well shaped function will then take time to also specify differences in the moment they're going to be coded. 

In my point of view: core has to be DRY... let me mention: undercover, spawn/despawn, win/loose, etc. 
So we have a scaffold that is solid and easy to read, and based on that we can add the specific subcategories that can actually be less shaped considering it's a mission of few mb and not a mod itself.

Also i'd give priority to parameters: it should be simple understand what is passed and how to call/spawn a function

**Comment by Barbolani77** [comment]
Well, I would start to build some basic functions like: [_soldiers, _marker] call isAbleToConquer > 3*([allUnits,_marker] call isAbleToDefend), or [_soldier] call isAbleToFight (not unconscious, alive, not captive, not fleeing), thos will simplify a lot of things.

**Comment by Sparker95** [comment]
One way I've learned to make "classes" and "objects" in SQF is:
1. Create any object which can be treated with setVariable and getVariable, like a logic unit or an object with a simple 3D model which you can later hide.
2. Then treat it like any object in OOP, make a "constructor", "destructor" for it and "methods" as usual functions.
It definitely keeps code more organized. But I have also found that the more objects like this you've created the longer time it takes to create a new one, simply the limitation of an engine(it's 10's of microseconds, IIRC, but still), and the (get/set)Variable performance might drop, so these objects shouldn't be created for every sneeze of your soldier.

**Comment by Souli7** [comment]
Maybe this repo can give you some insperation: https://github.com/dwringer/a3system
Found after some quick searching on github.
Love the work you put into Antistasi so maybe this will eventually help.

**Comment by zalexki** [comment]
Actually looks like OOP is not a real thing in SQF :/

I found this guide where some ideas can be applied for better readability : https://ace3mod.com/wiki/development/coding-guidelines.html

**Comment by zalexki** [comment]
Enfusion (DayZ and high chance arma 4) will support it \o/
I close because issue name actually is irrelevant to project.
