### ISSUE TITLE
Ace/Arsenal bug 

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#54]
*Version:* 1.0.0rc7

*Mods:* CBA, TFAR, ACE

*Environment*: MP dedi.

*.rpt attatched?* NO

*have you edited the missionfile?*: NO

***Проблема в следующем, если подключаешь обычный (нормальный) мод ACE то арсенал перестаёт нормально работать, профили не загружаются и в арсенале названия предметов, которые можно положить в рюкзак или разгрузку, накладываются друг на друга***

**Comment by Barbolani77** [comment]
Мы не видели эту проблему в тестах. У меня есть еще один отчет об этом провале, поэтому мы посмотрим на это. Думаю, вы говорите об ACE со всеми активированными опциями. Правильно ли это?

**Comment by AlexTriada** [comment]
да, правильно, спасибо за оперативность

**Comment by Barbolani77** [comment]
Я рассмотрю его сегодня

**Comment by Barbolani77** [comment]
Solved (AFAIK)
