### ISSUE TITLE
HQ composition dont saving after restart

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#56]
*Version:* 1.0.0

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: MP dedi

*.rpt attatched?* NO

*have you edited the missionfile?*: NO

***The problem with the movement of objects in HQ, after the server is restarted, the HQ objects are near the point, which is designated as HQ on the map, their arrangement after load save is reset, the commander is forced to reposition them, but the (exactly the same) problem arises: objects can not be moved, they "allegedly" are far from the point (flag), although they are actually near (this does not always happen)***

**Comment by Barbolani77** [comment]
Total minor issue. Soting the composition means storing more variables. We have to be extremely cautious doing so and keep this functionality only for important things.
