### ISSUE TITLE
[repository] multiple island compatibility

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#59]
*Version:* 1.0.0

Each island has its own:
A) mission.sqm (the map)
B) description.ext (name and characters voices)
C) pic.jpg (picture for intro and also displayed on map)

The rest of the code have to be the same

**Comment by Sparker95** [comment]
How do you like this:
Make a folder with all the scripts, like missions/WOTP/WOTP_common
Make folders for separate islands, like missions/WOTP/WOTP.altis, missions/WOTP/WOTP.tanoa, etc. They will only have the .ext and .sqm.
Make some .bat scripts to copy all the contents from WOTP_common to WOTP.altis, WOTP.tanoa?
You want to edit the .sqm in the editor - open the folder and edit it. When you want to have your code copied into the .island folder(for testing or exporting), run the script and that's all.
the .git folder will be located at the same level as the WOTP_common folder.

**Comment by StefArma** [comment]
A) we have missionAltis.sqm and missionTanoa.sqm  the user have just to rename to mission.sqm to have it working. there is also a gitignore for mission.sqm so, for testing purpose i've 2 hardlinks one named .Tanoa the other .Altis and i just switch the mission.sqm

**Comment by zalexki** [comment]
I think first we have to look if and how others do it, just check the source code/repositories of famous missions/mods (https://github.com/ALiVEOS, https://github.com/acemod/). i'll take a look next week but i dont know that much missions :/

**Comment by Sparker95** [comment]
Insurgency is a mission of similar kind:
https://github.com/Jigsor/BMR-Insurgency

**Comment by StefArma** [comment]
I had a chat with barbolani, he's going to use steam to pubblish anyway. 

So we can do like this: gitignore for mission.sqm, pic.jpg and description.ext
make 2 extra folders with the relative files

**Comment by Barbolani77** [comment]
What I am doing: I am using a master folder, which is Tanoa version.

This, on root has the Tanoa files.

Inside Templates folder I am adding folders named "cantRememberWorldName", so, when I copypaste it to other master folders (Altis edition, other worlds edition) I copypaste everything and after, extract those templates content in the root folder.

I have to just keep in mind to make backup in those folders if I change something on those files + keep in mind when I publish in Steam to do the double copy action.

But in case I publish wrong, it will be a matter of unPboing and taking the files.

Also it would be helpful if we attend Mr Peek forum posts about Antistasi media and unify PIC.jpg for all the versions.

I hope you get the point.
