### ISSUE TITLE
[error] garrisonUpdate.sqf, line 47

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#61]
*Version:* 1.0.0 (steamrelease)

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

    15:03:53 Error in expression < {garrisonIsChanging = false}; garrison setVariable [_marcador,_garrison,true]; >
    15:03:53   Error position: <setVariable [_marcador,_garrison,true]; >
    15:03:53   Error Reserved variable in expression
    15:03:53 File mpmissions\__cur_mp.Altis\CREATE\garrisonUpdate.sqf, line 47

**Comment by Barbolani77** [comment]
I'm lost on this too. Happened to me once. But I bulletproofed the function to avoid malfunctions.

**Comment by StefArma** [comment]
happened now with 1.0.4
