### ISSUE TITLE
[error] ataqueAAF.sqf, multiple lines

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#62]
*Version:* 1.0.0 (steamrelease)

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*:  MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***

    16:39:50 Error in expression <ves == 1) then { if (lados getVariable [_destino,sideUnknown] == buenos) then{ >
    16:39:50   Error position: <_destino,sideUnknown] == buenos) then { >
    16:39:50   Error Undefined variable in expression: _destino
    16:39:50 File mpmissions\__cur_mp.Altis\ataqueAAF.sqf, line 265

    16:39:50 Error in expression < = selectRandom _arrayFinal; _destino = _objetivoFinal select 0; _origen = _obje>
    16:39:50   Error position: <_objetivoFinal select 0; _origen = _obje>
    16:39:50   Error Undefined variable in expression: _objetivofinal
    16:39:50 File mpmissions\__cur_mp.Altis\ataqueAAF.sqf, line 260

    16:39:50 Error in expression <((tierWar - 3)/2)); }; }; }; }; if (not(_destino in ciudades)) then { [[_destino>
    16:39:50   Error position: <_destino in ciudades)) then { [[_destino>
    16:39:50   Error Undefined variable in expression: _destino
    16:39:50 File mpmissions\__cur_mp.Altis\ataqueAAF.sqf, line 295

**Comment by Barbolani77** [comment]
Weird, I would need more data to know what happened!

**Comment by StefArma** [comment]
Do i have the permission to rewrite the indentation of the file? i will mantain your structure, but i the indentation is a mess and i can't read it

    if () then
      {
          _var = a;
      }
     else
      {
       _var = b;
      };

**Comment by Barbolani77** [comment]
No pls. It makes me understand everything bettee

**Comment by StefArma** [comment]
ok

**Comment by Barbolani77** [comment]
Seems solved
