### ISSUE TITLE
[error] fn_logistics_unLoad.sqf, line 88

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#67]
*Version:* 1.0.1

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*:  MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

    17:24:06 Error in expression <ect setVariable ["ace_dragging_canDrag",_ace_dragging_canDrag];_object setVaria>
    17:24:06   Error position: <_ace_dragging_canDrag]; _object setVaria>
    17:24:06   Error Undefined variable in expression: _ace_dragging_candrag
    17:24:06 File JeroenArsenal\JNL\fn_logistics_unLoad.sqf [JN_fnc_logistics_unLoad], line 88

**Comment by Barbolani77** [comment]
solved in the next patch
