### ISSUE TITLE
[issue] APEX vehicles withAltis  RHS

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#68]
*Version:* 1.0.2

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

https://github.com/A3Antistasi/A3-Antistasi/blob/643c6a93905daab32bb5755b7afd93766bdf001f/A3-Antistasi/initVar.sqf#L167

this make use the APEX template, need a world check

civcar = "C_Offroad_02_unarmed_F"

**Comment by Barbolani77** [comment]
Altis check is done inside the templates. Check them.
