### ISSUE TITLE
[error] munitionTransfer.sqf, line 118

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#69]
*Version:* 1.0.2

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

    0:26:06 "Error en transmisión de munición. Tenía esto: <null> y estos contenedores: [], el origen era un "
    0:26:06 Error in expression <x == _arma} count _items); }; } forEach _items;if (count _itemsFinal > 0) then>
     0:26:06   Error position: <_items; if (count _itemsFinal > 0) then>
     0:26:06   Error Undefined variable in expression: _items
     0:26:06 File mpmissions\__cur_mp.Altis\Municion\munitionTransfer.sqf, line 118

**Comment by Barbolani77** [comment]
will add more debug notes to see what happens, seems strange the script fails at this point but not before
