### ISSUE TITLE
[error] Attack aircraft spawn on target

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#70]
*Version:* 1.0.2A

*Mods:* CBA, 

*Environment*: SP

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***
Test done by: gamestart, capture resoruce, eliminate qrf, save, load, forcing an attack of 1 wave 

12:28:58 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

**Comment by StefArma** [comment]
added for every line containing `_pos =`

diag_log format ["TESTATT: *linenumber* _pos = %1",_pos];

Considering that:
Attack departure airport = [11439.8,11709.2,0]
Attack destination = [5955.31,12531.1,0]


    13:02:22 "TESTATT: 383 _pos = [11439.8,11709.2,300]"
    13:02:29 "TESTATT: 489 _pos = [11439.8,11789.2,300]"
    13:02:35 "TESTATT: 446 _pos = [5762.53,11995.3,0]"
    13:02:36 "TESTATT: 489 _pos = [5762.53,12075.3,0]"
    13:02:36 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"
    13:02:43 "TESTATT: 489 _pos = [5762.53,12155.3,50]"
    13:02:43 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

**Comment by StefArma** [comment]
Another test: the first plane spawned correctly, the secon in wrong position: 

	13:07:01 "Antistasi: Waved attack from airport_4 to resource_6. Waves: 1"
	13:07:01 "Antistasi: Side attacker: WEST. Side defender (false, the other AI side):  true"
	13:07:01 "TESTATT: 215 _pos = [5955.31,13531.1,0]"
	13:07:01 "TESTATT: 215 _pos = [6955.31,12531.1,0]"
	13:07:01 "TESTATT: 215 _pos = [5955.31,11531.1,0]"
	13:07:01 "TESTATT: 215 _pos = [4955.31,12531.1,0]"
	13:07:01 "Antistasi: UAV B_UAV_02_F spawned. Number of vehicles 1"
	13:07:07 "TESTATT: 383 _pos = [11439.8,11709.2,300]"
	13:07:14 "TESTATT: 489 _pos = [11439.8,11789.2,300]"
	13:07:19 "TESTATT: 446 _pos = [5599.14,12359.6,0]"
	13:07:20 "TESTATT: 489 _pos = [5599.14,12439.6,0]"
	13:07:20 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

	13:07:27 "TESTATT: 489 _pos = [5599.14,12519.6,50]"
	13:07:27 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

	13:07:30 "TESTATT: 446 _pos = [5730.63,12200.9,0]"
	13:07:31 "TESTATT: 489 _pos = [5730.63,12280.9,0]"
	13:07:31 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"
	13:07:56 "TESTATT: 446 _pos = [6279.3,12822.3,0]"
	13:07:57 "TESTATT: 489 _pos = [6279.3,12902.3,0]"
	13:07:57 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

	13:08:04 "TESTATT: 446 _pos = [5840.18,13040.4,0]"
	13:08:05 "TESTATT: 489 _pos = [5840.18,13120.4,0]"
	13:08:05 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

	13:08:12 "TESTATT: 446 _pos = [6458.93,12180.8,0]"
	13:08:13 "TESTATT: 489 _pos = [6458.93,12260.8,0]"
	13:08:14 "Antistasi error al crear en posición incorrecta en wavedCA.Origen:airport_4.Dets:resource_6"

	13:08:16 "TESTATT: 446 _pos = [6331.33,12580.4,0]"
	13:08:17 "TESTATT: 489 _pos = [6331.33,12660.4,0]"
	13:08:17 "Antistasi: Arty Spawned"
	13:08:17 "Antistasi: Reached end of spawning attack, wave 0"

**Comment by StefArma** [comment]
Conclusion: Lines 446 and 489 cause the issue

    13:07:19 "TESTATT: 446 _pos = [5599.14,12359.6,0]"
    13:07:20 "TESTATT: 489 _pos = [5599.14,12439.6,0]"

**Comment by Barbolani77** [comment]
Great job Stef. Is one step forward to confirm the issue exists. I will try to find a solution.

**Comment by Barbolani77** [comment]
Ok, this error was in wavedCA and CSATpunish, no more should appear

**Comment by StefArma** [comment]
Done
