### ISSUE TITLE
[minor issue] Heavy rain in Altis

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#72]
*Version:* 1.0.2

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* Not relevant

*have you edited the missionfile?*: No

***Issue:***
Altis is very rainy because it's imported from tanoa settings: the tweak is: line 146 of mission.sqm changing it to:
`forecastWeather=0.050257543;`

funny that everyone complained because of always sunny Altis in the past... now, we've the opposite because it's hard to hear people over TFAR when raining a alot

**Comment by Barbolani77** [comment]
Solved with basic summer map config.
