### ISSUE TITLE
[Major Issue] 1.0.2B Huge server FPS drop

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#73]
*Version:* 1.0.2B

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: MP dedi.

*.rpt attatched?* haven't tested without HC

*have you edited the missionfile?*: No

***Issue:***
Something in the revive system causes server drop and stay to 7 FPS, i made a separate version with just files in folder \scriptSave and \CREATE   and the FPS drop doesn't show.

**Comment by Barbolani77** [comment]
What is the difference between versions?

**Comment by StefArma** [comment]
here: 

https://github.com/A3Antistasi/A3-Antistasi/pull/77/files

**Comment by StefArma** [comment]
basically, i removed everything you updated apart the \CREATE and \statsave  folders

**Comment by StefArma** [comment]
issue should be in
- actionrevive
- carry
- incosciente
- ayudar

**Comment by Barbolani77** [comment]
Will check. Maybe some waituntil should have an sleep

**Comment by Sparker95** [comment]
I have seen some correlation with this thing:
I spawn in airfield and this happens:
https://steamuserimages-a.akamaihd.net/ugc/911295377051263142/38CCA367B5AEDF9C3EE22C3E1D255AE5A472143C/
https://steamuserimages-a.akamaihd.net/ugc/911295377051262009/6ACCA5E5907D6CCA8FB26DDAA4209A3B1BF9C1F8/
Units of both sides spawn at the top of each other and start killing each other. Server FPS instantly drops. I despawn the area and it's fine again. I was able to reproduce it a few times.
When it happened the airfield and its outpost were on CSAT side.

**Comment by Barbolani77** [comment]
Makes sense. If you have a massive unit injury you have a massive loop generation? I Will modify spawngroup so Ill allowdmage false every unit until the whole group has spawned

**Comment by Barbolani77** [comment]
Solved?

**Comment by StefArma** [comment]
Looks so ;) i saw them fighting, fps drop, then go up again when the fight stop

**Comment by Barbolani77** [comment]
Nah, we have recent fórum reports on this.


I bet is patrolReinf.sqf.
More specifically this:
while {_landPos isEqualTo [0,0,0]} do

		{

		_landPos = [_posDestino, 0, _maxDist, 10, 0, 0.20, 0,[],[[0,0,0],[0,0,0]]] call BIS_fnc_findSafePos;

		_maxDist = _maxDist + 50;

		};
That function is CPU eater.
I use one single iteration of this in waved and patrol CA
I will put the same solution: one iteration and, if position is not found, fastrope.

**Comment by Sparker95** [comment]
I'd use exponential increase instead. For instance increase the radius by 40% each time, it should converge much faster.

**Comment by Barbolani77** [comment]
Can be, but that function is tricky, and in case it fails several times, you Will ask the function to search for a 1Kmt radius = server burnt.

Easier to make the AI rappel, faster, less CPU use...

**Comment by StefArma** [comment]
agree, landing is bad anyway

**Comment by Barbolani77** [comment]
So you mean when the server is flooded, do a copyToClipboard str diag_activeSQFScripts and see the lines if they are in some while loop or something?

Does your files been exported while in a FPS drop? If yes, apart of a few checks here and there, I don't think we Will find something.

About the BIS_fnc_SafePos function: believe me, it has the capacility of destroying a PC while not reporting anything in .rpt Happened in early stages of WotP as I discovered (after breaking my head) Antistasi had a bad call on those which in certain situations flooded the PC.

I changed patrolReinf to admit paradroping and fatsroping to avoid more tan one call.

**Comment by Sparker95** [comment]
> So you mean when the server is flooded, do a copyToClipboard str diag_activeSQFScripts and see the lines if they are in some while loop or something?

Yes but I did it at the server, then grabbed the result and saved it into these files. I thought you should rather examine them, you have a higher chance to find something strange.

> Does your files been exported while in a FPS drop?

Yes, I also have some recorded without this FPS drop.

> About the BIS_fnc_SafePos function: believe me, it has the capacility of destroying a PC
Yes it's important on its own but the files I've attached show no scripts that are using this BIS_fnc_findSafePos function, so it can't be the reason of this problem.

**Comment by Barbolani77** [comment]
Good! Ill check.

almost everything is postmortem, a pure sleep + deletevehicle, if is this, I retire :)

**Comment by Barbolani77** [comment]
Uhm, first thing: Why UPSMon track was activated, did you? because that is monitoring every 0.5 secs a bunch of groups and it is for debugging purposes.

**Comment by Sparker95** [comment]
I can swear to Zeus that I have never touched any WOTP code, nor I activated any scripts myself, including the UPS track.

**Comment by Barbolani77** [comment]
dummdummm very weird

**Comment by Barbolani77** [comment]
its definetly that, Im going to remove the function, as only Stef uses it from time to time

**Comment by Barbolani77** [comment]
To be honest I don't think it is the cause. It is intensive, yes, but no more than distancias4.sqf, and that kind of things, with proper delays, never floods a server.

**Comment by Sparker95** [comment]
It came to my mind that we have already had this thing before in the community version.
So, half a year ago I've discovered that there is a smoke deployment attached to "HandleDamage" event handler. When you hit or destroy a vehicle its event handler gets triggered ~10...100 times, also include the event flood when ACE cookoff gets triggered and it starts receiving dammage from all these tiny explosions of ammunition, causing it to deploy thousands of smoke grenades!
Check this and similar lines:
https://github.com/A3Antistasi/A3-Antistasi/blob/f1098b38be4e774b24fa5634201703d1853afaf5/A3-Antistasi/CREATE/AIVEHinit.sqf#L44
https://github.com/A3Antistasi/A3-Antistasi/blob/f1098b38be4e774b24fa5634201703d1853afaf5/A3-Antistasi/CREATE/AIVEHinit.sqf#L64
We are currently testing if commenting out these resolves the performance drop.

**Comment by Barbolani77** [comment]
It can be but I doubt it. Despite yes, it's better to remove those EH at some point (HD EH stays even when the vehicle is not alive), the smokescreen script checks for alive and puts some timeOut for better timing spacing of the smokescreens, so it shouldnt be that.

Even more: I remember in your reports you or Stef said there was very few vehicles in map, or even none.

**Comment by Sparker95** [comment]
But the performance drop happened after we fought with AIs a little bit, but then it persisted after AIs got despawned.
We can test the theory very easy, there must be a command which returns the amount of vehicles of certain type (grenade in this case) in the scene.

**Comment by Barbolani77** [comment]
well, my suggestion: just comment those lines, losing that feature is not a game breaking, just a few APCs found with punctured wheels and no smoke when you damage them. If everything runs well since that, then we have our suspect nº 1.

**Comment by Barbolani77** [comment]
Hi! I updated the server with a version which removes HD EHs on kill and when they pop up smoke. If it's the issue, we will now. Pls report.

**Comment by Barbolani77** [comment]
So it was Nitrado fault?

AFAIK I have no other reports on this in steam, so now it's suspect number one

**Comment by Sparker95** [comment]
Looks like so. Wurm's server showed much better performance. At least FPS didn't drop to 2 or 3.

**Comment by Barbolani77** [comment]
Hey!

Did you know about this command? Someone in BIS fórums sent this on my request about this issue:

https://community.bistudio.com/wiki/diag_captureSlowFrame

Maybe you pros know how to use :)

**Comment by Sparker95** [comment]
It can only be used with a special performance executable of ARMA(no way **trado will let us start a different executable of the game) and as I understand it will perform this action only on the current machine, while we need to understand what's happening at the server.

**Comment by zalexki** [comment]
oh ye i forgot about the debug arma i tried in SP (Even if didnt really understand anything) i thought we might cheat it on logs with a remoteExec but ye need special arma :/

**Comment by Barbolani77** [comment]
Lets say this is solved and it was a hardware malfunction
