### ISSUE TITLE
[MajorIssue] in Altis: Greenfor and Opfor are allied

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#74]
*Version:* 1.0.

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***

https://github.com/A3Antistasi/A3-Antistasi/blob/1cde46509a0b11e5bae4a32ebf7667fa7a38d684/A3-Antistasi/missionAltis.sqm#L143

CSAT won't shoot player
need to be changed to 0

**Comment by Barbolani77** [comment]
Lol! That happens because I used the 1.8 as misión.sqm template. Enjoy killing NATO during the weekend. Stef pls post this un Steam And recommend ppl yo join official if they come to later stages
