### ISSUE TITLE
[minor - template] AFRF

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#75]
*Version:* 1.0.2

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*:MP dedi.

*.rpt attatched?* Nothing relevant

*have you edited the missionfile?*: No

***Issue:***

- Opfor at Aggr.100 aren't equipping NVGs in Outpost

- AFRF attack sent 7 jets for an outpost, i tought jets were removed for attack, they are performance demanding and not that useful.

**Comment by Barbolani77** [comment]
Aggro is not related to nvg equip

If I remember well jets were removed from qrf, not Major attack. They can be useful there.

**Comment by StefArma** [comment]
i'd remove them from major attack too, or at least, limit to 1 per wave... they keep flying spawning and despawning units which is still an issue if the server is populated or if player is fighting in a high density zone
