### ISSUE TITLE
When you Accidently hit an AI Squad Mate, they will throw you out of the group and kill you

### ISSUE THREAD

**Issue by gallexme** [A3Antistasi/A3-Antistasi#76]
When u accidently damage an AI in your group, u get kicked off the group and they start to hunt you

:(

**Comment by Barbolani77** [comment]
That is vanilla behaviour

**Comment by gallexme** [comment]
it never happend with the none wotp antistasi @Barbolani77

**Comment by Barbolani77** [comment]
Go to editor. Place one group. Make one unit playable. Play. Kill a couple teammates. See them attacking you. Pay me one spirit because of the "It never happens"

**Comment by gallexme** [comment]
@Barbolani77 
well yes then it happens,
but in the mission when u slightly hit your teammate which needs a revive, they all go against you instantly, after 1 shot, gonna try to record it

**Comment by gallexme** [comment]
also sometimes after u get die, one of the AI gets the group leader and doesnt step down once u revived

**Comment by gallexme** [comment]
How it Always was in old Antistasi and how it normally is:
https://www.youtube.com/watch?v=Nr6IhbBMo1s&feature=youtu.be

After Mission Restart and finding an Enemy:

When your squad mate dies from an enemy and u "accidently" hit him
https://www.youtube.com/watch?v=nmmqTr8XAjQ&feature=youtu.be

they kick you out and directly kill you

**Comment by Sparker95** [comment]
I certainly remember when I was looking through the old antistasi code, I think in one of the 'killed' event handlers, there were a few linex that returned you score for killing friendlies. Maybe it was coded in by Chris or someone else.
How it works in default arma: if you kill friendlies you lose score. If score gets below certain threshold you are automatically switched to "enemy" side, which is like the nemy of all the people and everyone will attack you.

**Comment by gallexme** [comment]
in the second video it was the first time since mission startup i did a team member damage, maybe that score calculation is weird when the team member needs to be revived?
