### ISSUE TITLE
[minor issue] Roadblock setup condition

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#80]
*Version:* 1.0.3

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
- Roadblock setup is considered successful if driver arrive with or without the vehicle (so player tie up the guy bring him to  roadblock location and a vehicle will appear. can the check be on the alive and  position vehicle instead?
- the roadblock vehicle is a truck and at the roadblock there will be the armed offroad can line 20 of crearpuestofia be replaced with vehSDKLightArmed ?

---

(optional) request:
- create roadblock and OP are separated and just create the HC group, no position on map or task.
- shift ctrl Y on roadblock group selected = check if is on road and then deploy
- remove roadblock create a group in RB position and send the eventual added garrison back to HQ

**Comment by Barbolani77** [comment]
As it is a mix of AT squad and armed vehicle, I chose one, :9
