### ISSUE TITLE
[Error] taskUpdate.sqf, line 8

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#81]
*Version:* 1.0.3

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***

     16:06:48 Error in expression < (((_descriptionOld select 1) select 0) != (_description select 1)) then{ _solo>
     16:06:48   Error position: <!= (_description select 1)) then { _solo>
     16:06:48   Error Generic error in expression
     16:06:48 File mpmissions\__cur_mp.Altis\Missions\taskUpdate.sqf, line 8

**Comment by Barbolani77** [comment]
Without more info Im afraid this one will be on hold
