### ISSUE TITLE
[Error] fn_logistics_getCargoOffsetAndDir.sqf line 22 & 54

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#82]
*Version:* 1.0.4

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

    20:35:48 ["node",1]
    20:35:48 Error in expression <peNode] call jn_fnc_logistics_getNodes) select _nodeID) select 0; private _ob>
    20:35:48   Error position: <select _nodeID) select 0; private _ob>
    20:35:48   Error Zero divisor
    20:35:48 File JeroenArsenal\JNL\Functions\fn_logistics_getCargoOffsetAndDir.sqf [JN_fnc_logistics_getCargoOffsetAndDir], line 22

**Comment by StefArma** [comment]
This related too

    20:36:02 Error in expression <vate _yEnd = _bbv + _bbo - 0.1; while {_loc1 select 1 > _yEnd}do{ sleep 0.1; _l>
    20:36:02   Error position: <_loc1 select 1 > _yEnd}do{ sleep 0.1; _l>
    20:36:02   Error Undefined variable in expression: _loc1
    20:36:02 File JeroenArsenal\JNL\fn_logistics_unLoad.sqf [JN_fnc_logistics_unLoad], line 54

**Comment by Sparker95** [comment]
Need to know more about how this happened and what was the observed effect.
