### ISSUE TITLE
Outpost becomes impossible to capture

### ISSUE THREAD

**Issue by VenomSnake1985** [A3Antistasi/A3-Antistasi#85]
Version 1.0.4 - MP official server.

There is a specific outpost on the server that cannot e captured, even if all the A.I around have been completely cleared, the outpost isn't captured. It is not possible to take the flag either. Other outposts work fine, but this specific one doesn't seem to work,, Issue still persists after server restart

**Comment by Barbolani77** [comment]
Please provide more info. Specific post At least And What happens when capturing the flag

**Comment by VenomSnake1985** [comment]
On our current campaign on the main server, there is one specific outpost that we can take. We have gone up there and cleared it completely (check o spectator to make sure there was no A.I we where missing), and we weren't getting the capture. We where also unable to capture the flag.

To be specific the one we cant take is located on the north east tide of Altis, top of the right half of the island. Right now it seems to be that specific one, but players tell me theres een other outposts like this.

**Comment by Barbolani77** [comment]
Will test, but if I cannot rperoduce you Will have to provide more info. What happens when you cap the flag? No option appears or it appears but nothing happens?

**Comment by zalexki** [comment]
The one time that's happenned to me, we had the option and the animation was launched then it was just doing nothin or show the message ennemy is near.
Might be related to the HQ one where there is still ennemies near? some wrong deleted object/vehicule or just wrong condition at all maybe ?

**Comment by Barbolani77** [comment]
I think we can close this
