### ISSUE TITLE
Error Undefined variable _posicion in AI/airdrop.sqf

### ISSUE THREAD

**Issue by zalexki** [A3Antistasi/A3-Antistasi#87]
*Version:* 1.0.8

*Mods:* CBA, TFAR, ACE(no-medical), RHS and all others

*Environment*: MP dedi official EU 2 (wurm server)

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***
Errors in RPT logs on (server and HC1) official EU 2, this spam a lot !!!! like a really lot
We deleted some AIs for perf so now the script never end ? 

```while {true} do
{
_landpos = _posicion getPos [_dist, _randang];
if (>
19:17:20   Error position: <_posicion getPos [_dist, _randang];
if (>
19:17:20   Error Undefined variable in expression: _posicion
19:17:20 File mpmissions\__cur_mp.Altis\AI\airdrop.sqf, line 27
19:17:20 Error in expression <ndom 360;
```

EDIT: https://github.com/A3Antistasi/A3-Antistasi/blob/master/A3-Antistasi/AI/airdrop.sqf#L24
can you fix this while true? 
we need to find something to test in order to not have endless scripts. (maybe `_veh`  ?)

**Comment by Barbolani77** [comment]
uhm, strange, I reviewed all the script calls, they are correct, and, if it's sending wrong values, it should appear somewhere else.

About the loop. If "well fed" is not problematic, no area in the whole map has water all around 500 mts.

**Comment by Barbolani77** [comment]
No worries, got the bug during my tests and will be solved in the next patch. Its related to reinforcements.

**Comment by zalexki** [comment]
Concerning the `while {true}`, we got 700mb logs in half a day ... (pls staaaaaap using this `while {true}` this is the worst of all, we got waitUntil{}, EH, while with conditions to properly do what a while true does)
Not only the script will run for ever and ever for nothing, it will multiply every time a reinf fail if i understand correctly ?

So actually we got 2 issue to fix here, one is to properly call the function and the second is to fix this possible 'cpu leak' in the function itself.

What do you think ?

**Comment by Barbolani77** [comment]
if drops error it's problematic, but it wont do it anymore.

The fps flood is not related as this bug comes from a recent change.

**Comment by zalexki** [comment]
`if drops error it's problematic, but it wont do it anymore.`  *it shouldn't* do it anymore :p 
You must now have enough experienced that coding never go as planned, especially in arma :smile:  

You're talking about the 3 fps issue ? didnt get real low fps during these errors, got a small drop when AIs spawn and are still in air but goes to normal after landing nothing weird.

If you're talking about the RPT flood i dont understand your point. I got this error in RPT during a `tail -f ` so i can say there is no doubt this is what was flooding ;)
