### ISSUE TITLE
[question] Mover aa estatico/ how move AA static or AT static RHS

### ISSUE THREAD

**Issue by Raptorkoda** [A3Antistasi/A3-Antistasi#89]
*Version:* 1.4

*Mods:* FFAA, RHS, ACE(no-medical)

*Environment*:MP dedi.
*have you edited the missionfile?*: No

Mi pregunta es si se puede mover de alguna manera las AA estaticas de RHS ya que hemos buscado en distintos lados y no encontramos ni en RHS la respuesta ni en ningun foro. de no existir opcion se puede ingresar algun script o opcion para moverlas?/ My question is whether the static AAs of RHS can be moved in any way since we have searched in different places and we did not find the answer or in any forum in RHS. if there is no option, can you enter some script or option to move them? (google translator)

**Comment by Barbolani77** [comment]
Hola! No. Es una limitación de RHS, ni tienen la función de desmontar ni tienen las classnames de portadores de estáticas, lo que va a afectar a la próxima versión.

Creo que ACE tiene una función de interacción.
