### ISSUE TITLE
Top progress bar not showing

### ISSUE THREAD

**Issue by zalexki** [A3Antistasi/A3-Antistasi#90]
*Version:* `antistasiVersion = "v 1.1.0";`

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: MP dedi nitrado

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***
Top bar with infos as commander and others dont show up, tried to restart game/pc do nothing.

[Arma3_x64_2018-06-06_23-31-53.txt](https://github.com/A3Antistasi/A3-Antistasi/files/2078283/Arma3_x64_2018-06-06_23-31-53.txt)

Restarted server and it worked but seems totally random bug

**Comment by zalexki** [comment]
As my RPT show i have an undefined `H8erHUD`(wtf does that mean ?)

So what about this [waitUntil](https://github.com/A3Antistasi/antistasi-1.x/blob/88777ea7a0ba5cddbd9c52d6748feaeceeb94508/AntistasiOfficial.Altis/statistics.sqf#L9) ? he might ensure that this is correctly set

**Comment by Barbolani77** [comment]
Will try

**Comment by Barbolani77** [comment]
I bulletproofed the function a bit, to avoid errors when that variable is nil and when the commander variable is nil

**Comment by Barbolani77** [comment]
I think with all the init fixes this is solved.

**Comment by zalexki** [comment]
[Arma3_x64_2018-07-05_18-27-59.txt](https://github.com/A3Antistasi/A3-Antistasi/files/2167465/Arma3_x64_2018-07-05_18-27-59.txt)
Got it on EU 1 v1.1.4

**Comment by Barbolani77** [comment]
Hi!

I just published a patch which I suppose it will solve this. Pls confirm.

**Comment by zalexki** [comment]
fixed \o/
