### ISSUE TITLE
AI load balancing HC not properly working

### ISSUE THREAD

**Issue by zalexki** [A3Antistasi/A3-Antistasi#94]
*Version:* 1.0.0

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*: MP nitrado

*.rpt attatched?* no

*have you edited the missionfile?*: No

***Issue:***

![ai-loadbalancer](https://user-images.githubusercontent.com/3863527/41157090-c80c756e-6b24-11e8-9ece-d5d3323d5703.jpg)
![ai-loadbalancer2](https://user-images.githubusercontent.com/3863527/41157091-c8259882-6b24-11e8-8b59-3b740a39caaf.jpg)

As you can see the HCs units goes up and down but are not evenly spread accross HCs.

Maybe linked to cached system that bypass the load balancing system ?

**Comment by Barbolani77** [comment]
Very few things bypass the scheduler. Just make a patrolCA check to see if I misses a call.

Also: balancing is related to scripts, so you may find Big differences un case a HC has been ordered to execute a Major attacks.

**Comment by Barbolani77** [comment]
Excuse the typos. Damm cell phone
