### ISSUE TITLE
Admin crash when loading game on dedi

### ISSUE THREAD

**Issue by bobchaos** [A3Antistasi/A3-Antistasi#99]
*Version:* 1.1.0

*Mods:* CBA, TFAR, ACE(no-medical), RHS USAF GREF AFRF

*Environment*: Dedi

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***
Admin game client crashes when he attempts to load the mission with auto-load enabld and causes all other clients to hang. If the admin does alt+f4 the server resumes and all other players are allowed on no problem. The admin can restart is game client and log in normally after.

This can be easily reproduced like this:
- Log on a dedicated server
- login as admin
- do #missions
- select antistasi and leave auto-load option on (default)
- hit continue
- wait for crash, the alt+f4
[arma3server_x64_2018-06-13_01-51-36.zip](https://github.com/A3Antistasi/A3-Antistasi/files/2096244/arma3server_x64_2018-06-13_01-51-36.zip)

**Comment by AlexTriada** [comment]
скажу ещё по секрету, что загрузка сохранения денег, гаража и звания игрока тоже не работает

**Comment by Barbolani77** [comment]
I need admin client .rpt

I have another report of this in Steam, so it seems caused by Antistasi.

**Comment by szimre** [comment]
It does not crash for me, however it stops loading and I have to quit on the client and rejoin.
Admin RPT hangs at "Antistasi MP Client. Waiting for serverInitDone"
and waitUntil {!isNil"statsLoaded"}; in initServer.sqf:80 does not progress on the server side after _nul = [] execVM "statSave\loadAccount.sqf"; gets called.

If it does work I get errors like this in the server log: "La variable tasks no existe en el entorno tasks31935WotP" and the player money resets to 100. (not sure if it's supposed to save gear, hope it does, but everything player related resets, so you lose whatever you had on you)
